version: '3.8'

services:
    text-explorer:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "10000:10000"
        depends_on:
            - qdrant
        networks:
            - app-network
        volumes:
            - ./onnx:/app/onnx
            - ./sqlite_database.db:/app/sqlite_database.db:z

    qdrant:
        image: qdrant/qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - ./qdrant_storage:/qdrant/storage:z
        networks:
            - app-network

networks:
    app-network:
        driver: bridge